name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: move to dockerfile directory
      run: cd dockerfile
    - name: Build the Docker image
      run: docker build -t ml:latest .
    - name: Run Docker image
      run: docker run -d -p 5000:5000 ml
    - name: stop running Docker image
      run: docker rmi $(docker images -q)
    - name: remove build cahce
      run: docker system prune
