name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./dockerfile

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -t ml:latest .
    - name: Run Docker image
      run: docker run -d -p 5000:5000 ml
    - name: See if Docker image is running
      run: curl http://localhost:5000/predict
    - name: remove build cahce
      run: docker system prune
